# Religion, Magic and Metaphysics

> There are more things in the world than are dreamed of in your philosophy.

What exactly exists? Is this world of stuff, the natural or material world as studied and further categorized by science, all that there is to reality? Or is the material world just one aspect of reality with other, far less tangible but equally real, domains also part of reality? Are spirits, ghosts, gods, or God real? What about numbers, concepts and other abstract "things" -- are they arbitrary symbols for patterns in material things, or do they possess a kind of substance of their own, a reality that is not so much invented by beings capable of grasping abstractions as it is discovered and explored by them?

These are all deep and difficult questions to try to address, and it has been one of the historical preoccupations of philosophers to try to answer them. Doing so has led to the development of a complex and highly technical vocabulary and conceptual apparatus that is often referred to as "metaphysics," or "ontology." But these questions have been central to the project of philosophical self-examination since they have to do with one of the fundamental ways in which our thinking works -- by distinguishing between kinds of things, classifying and categorizing them. This is such a central component of our meaning-making minds that we hardly ever notice it at work. But that it is there and that it is a crucial component of any thinking at all becomes clear when the categories we rely on to make sense of things no longer work as they once did. Fundamental challenges to the basic categories we rely on are somewhat rare, but they do occur from time to time in the lives of individuals, cultures and civilizations.

Take as an example the enormous and persistent backlash against Darwin's theory of evolution that first appeared in Europe and America immediately after the publication of Darwin's great work *On the Origin of Species* in 1859 and continues to this day, more than 150 years later. Darwin's basic theoretical idea, that living organisms on the planet Earth form one big extended family tree that has diversified and changed over time largely through a process called "natural selection" is central to the entire field of biology in the same way that atomic theory is central to chemistry, or the way the notions of matter and energy are central to physics. Nothing in biology makes any sense at all with it. And yet, many people outright reject the idea that organisms have evolved over the vast stretches of time that make up the history of life on Earth. And they do so for reasons having to do with the way it challenges fundamental assumptions we have about basic categories -- humans as opposed to animals, blind mechanical and material processes as opposed to intentional and meaningful actions, the animate as opposed to the inanimate.

## "Being" Means Many Things

## Arguing About God

## Magical Thinking

